### ISSUE TITLE
zfs requirements

### ISSUE THREAD

**Issue by tristan-k** [Wladimir-N/pve-zfs-clone#6]
I'm trying to use the script on `Proxmox 7.1 (5.11.22-7-pve)` but it fails due to a zfs version mismatch. Can you specify which zfs version is required to run `pve-zfs-clone` or make it compatible with recent zfs versions on Proxmox?

```
$ ./pve-zfs-clone/pve-zfs-clone
Не соответствие версий ZFS, проверьте вывод команды 'zfs version'. Вероятно необходимо сделать перезагрузку сервера.
$ zfs version
zfs-2.1.2-pve1
zfs-kmod-2.0.6-pve1
```

**Comment by Wladimir-N** [comment]
У Вас не соответствие версий установленных и запущенных пакетов. Выполните перезагрузку сервера чтобы подгрузились новые. Проверка сделана не просто так, иногда такое не соответствие приводит к проблемам создания клонов.

You have a mismatch between the versions of installed and running packages. Reboot the server to load the new ones. The check was done for a reason, sometimes such a mismatch leads to problems creating clones.
